version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop-vulnerable-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s 